'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace FACT

    Partial Public Class Certificados

        Protected WithEvents lblEstadoActual As Global.System.Web.UI.WebControls.Label

        Protected WithEvents fuCer As Global.System.Web.UI.WebControls.FileUpload

        Protected WithEvents fuKey As Global.System.Web.UI.WebControls.FileUpload

        Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

        Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button

        Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
